name: Build and deploy workflow
on: [ push ]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t pulsercoder/skypro_pkuzmin_game:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push pulsercoder/skypro_pkuzmin_game:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: deploy app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd flask_app_game
            echo ${{ secrets.PASSWORD }} | sudo -S docker pull -d pulsercoder/skypro_pkuzmin_game:$GITHUB_REF_NAME-$GITHUB_RUN_ID
            echo ${{ secrets.PASSWORD }} | sudo -S docker run -d pulsercoder/skypro_pkuzmin_game:$GITHUB_REF_NAME-$GITHUB_RUN_ID